package resources

import (
	istioapi "github.com/bevyx/istio-api-go/pkg/apis/istio/v1alpha3"
	api "github.com/bevyx/remesh/pkg/apis/remesh/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

func MakeIstioGateway(entrypoint api.Entrypoint, namespace string) (istioapi.Gateway, string) {
	istioServers := make([]istioapi.Server, 0)

	for _, server := range entrypoint.Spec.Servers {

		istioServers = append(istioServers, istioapi.Server{
			Port: istioapi.Port{
				Name:     server.Port.Name,
				Number:   server.Port.Number,
				Protocol: server.Port.Protocol,
			},
			Hosts: server.Hosts,
			Tls: istioapi.Server_TLSOptions{
				HttpsRedirect:     server.Tls.HttpsRedirect,
				Mode:              istioapi.Server_TLSOptions_TLSmode(server.Tls.Mode),
				ServerCertificate: server.Tls.ServerCertificate,
				PrivateKey:        server.Tls.PrivateKey,
				CaCertificates:    server.Tls.CaCertificates,
				SubjectAltNames:   server.Tls.SubjectAltNames,
			},
		})
	}
	gatewaySpec := istioapi.GatewaySpec{
		Selector: map[string]string{"istio": "ingressgateway"},
		Servers:  istioServers,
	}

	gatewayName := Prefix + entrypoint.Name + GatewaySuffix

	gateway := makeGateway(gatewayName, gatewaySpec, entrypoint)

	return gateway, gatewayName
}

func makeGateway(name string, gatewaySpec istioapi.GatewaySpec, entrypoint api.Entrypoint) istioapi.Gateway {
	return istioapi.Gateway{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Gateway",
			APIVersion: "networking.istio.io/v1alpha3",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: entrypoint.Namespace,
			OwnerReferences: []metav1.OwnerReference{
				*metav1.NewControllerRef(&entrypoint, schema.GroupVersionKind{
					Group:   api.SchemeGroupVersion.Group,
					Version: api.SchemeGroupVersion.Version,
					Kind:    "Entrypoint",
				}),
			},
			Labels: AutoGeneratedLabels,
		},
		Spec: gatewaySpec,
	}
}
