package resources

const (
	//Prefix is
	Prefix = "remesh-"
	//GatewaySuffix is
	GatewaySuffix = "-gateway"
	//VsSuffix is
	VsSuffix = "-vs"
	//DsSuffix is
	DsSuffix = "-ds"
	//AutoGeneratedLabelName is
	AutoGeneratedLabelName = "remesh.bevyx.com/auto-generated"
	//AutoGeneratedLabelValue is
	AutoGeneratedLabelValue = "true"
)

//AutoGeneratedLabels is
var AutoGeneratedLabels = map[string]string{
	AutoGeneratedLabelName: AutoGeneratedLabelValue,
}

//GetSubsetName is
func GetSubsetName(host string, subsetHash string) string {
	return host + "-" + subsetHash
}

const (
	//HostAll is
	HostAll = "*"
	//Mesh is
	Mesh = "mesh"
)
