package resources

import (
	istioapi "github.com/bevyx/istio-api-go/pkg/apis/istio/v1alpha3"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func MakeIstioVirtualServiceForGateway(httpRoutes []istioapi.HTTPRoute, namespace string, gateway string) istioapi.VirtualService {
	name := gateway + VsSuffix
	return istioapi.VirtualService{
		TypeMeta: metav1.TypeMeta{
			Kind:       "VirtualService",
			APIVersion: "networking.istio.io/v1alpha3",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			/*OwnerReferences: []metav1.OwnerReference{
				*metav1.NewControllerRef(&entrypoint, schema.GroupVersionKind{
					Group:   api.SchemeGroupVersion.Group,
					Version: api.SchemeGroupVersion.Version,
					Kind:    "VirtualEnvironment",
				}),
			},*/
			Labels: AutoGeneratedLabels,
		},
		Spec: istioapi.VirtualServiceSpec{
			Hosts:    []string{HostAll},
			Gateways: []string{gateway},
			Http:     httpRoutes,
		},
	}
}
