apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: destinationrules.istio.bevyx.com
spec:
  group: istio.bevyx.com
  names:
    kind: DestinationRule
    plural: destinationrules
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            host:
              type: string
            subsets:
              items:
                properties:
                  labels:
                    type: object
                  name:
                    type: string
                type: object
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1alpha3
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
