apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: releases.remesh.bevyx.com
spec:
  group: remesh.bevyx.com
  names:
    kind: Release
    plural: releases
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            layout:
              type: string
            targeting:
              properties:
                priority:
                  format: int32
                  type: integer
                segments:
                  items:
                    type: string
                  type: array
              type: object
            virtualAppConfig:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
