apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: virtualapps.remesh.bevyx.com
spec:
  group: remesh.bevyx.com
  names:
    kind: VirtualApp
    plural: virtualapps
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            releaseFlows:
              items:
                properties:
                  layout:
                    properties:
                      http:
                        items:
                          properties:
                            destination:
                              properties:
                                host:
                                  type: string
                                port:
                                  properties:
                                    number:
                                      format: int32
                                      type: integer
                                  type: object
                              type: object
                            match:
                              items:
                                properties:
                                  authority:
                                    properties:
                                      exact:
                                        type: string
                                      prefix:
                                        type: string
                                      regex:
                                        type: string
                                    type: object
                                  gateways:
                                    items:
                                      type: string
                                    type: array
                                  headers:
                                    type: object
                                  method:
                                    properties:
                                      exact:
                                        type: string
                                      prefix:
                                        type: string
                                      regex:
                                        type: string
                                    type: object
                                  port:
                                    format: int32
                                    type: integer
                                  scheme:
                                    properties:
                                      exact:
                                        type: string
                                      prefix:
                                        type: string
                                      regex:
                                        type: string
                                    type: object
                                  uri:
                                    properties:
                                      exact:
                                        type: string
                                      prefix:
                                        type: string
                                      regex:
                                        type: string
                                    type: object
                                type: object
                              type: array
                          type: object
                        type: array
                      services:
                        items:
                          properties:
                            host:
                              type: string
                            labels:
                              type: object
                          type: object
                        type: array
                    type: object
                  layoutName:
                    type: string
                  release:
                    properties:
                      layout:
                        type: string
                      targeting:
                        properties:
                          priority:
                            format: int32
                            type: integer
                          segments:
                            items:
                              type: string
                            type: array
                        type: object
                      virtualAppConfig:
                        type: string
                    type: object
                  releaseName:
                    type: string
                  segments:
                    type: object
                type: object
              type: array
            virtualAppConfig:
              properties:
                servers:
                  items:
                    properties:
                      hosts:
                        items:
                          type: string
                        type: array
                      port:
                        properties:
                          name:
                            type: string
                          number:
                            format: int32
                            type: integer
                          protocol:
                            type: string
                        type: object
                      tls:
                        properties:
                          mode:
                            type: string
                        type: object
                    type: object
                  type: array
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
